"""empty message

Revision ID: 102373ebd8da
Revises: 21610bca3651
Create Date: 2023-02-08 23:01:41.730405

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '102373ebd8da'
down_revision = '21610bca3651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('date', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('date', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.String(),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=True)

    # ### end Alembic commands ###
